### ISSUE TITLE
Pathfinder deforms Cantarell

### ISSUE THREAD

**Issue by heftig** [pcwalton/pathfinder#100]
Pathfinder misshapes Cantarell, a CFF font, exaggerating smooth curves into corners.

http://ftp.gnome.org/pub/gnome/sources/cantarell-fonts/0.111/

WR + Pathfinder:
![screenshot from 2018-11-09 00-17-40](https://user-images.githubusercontent.com/204006/48233841-1bd0f700-e3b7-11e8-9509-fbb1a55e3cd9.png)

Non-WR:
![screenshot from 2018-11-09 00-17-44](https://user-images.githubusercontent.com/204006/48233846-1ecbe780-e3b7-11e8-9af7-80f7906306a5.png)

Firefox Nightly
Arch Linux

**Comment by pcwalton** [comment]
Closing this as no longer relevant to Pathfinder 3, though we will need to remember to test Cantarell so we don't cause the issue again.
