### ISSUE TITLE
Demo Build Error 

### ISSUE THREAD

**Issue by igagen** [pcwalton/pathfinder#103]
I'm getting the following error when running `npm run build`:

```
error[E0599]: no variant named `concat` found for type `syntax::tokenstream::TokenStream` in the current scope

   --> /Users/igagen/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:330:54
    |
330 |                 mac.node.tts = ThinTokenStream::from(TokenStream::concat(streams));
    |                                                      ^^^^^^^^^^^^^^^^^^^ variant not found in `syntax::tokenstream::TokenStream`
```

I've updated everything to the latest (running on Mojave):

`rustc 1.33.0-nightly (e40548bc4 2018-12-21)`
`node v11.5.0`

I've also done a brew update/upgrade and `cargo update` as well.

Any ideas how to get past this?

**Comment by marschr** [comment]
Hi there.
I got the same error few minutes ago and just fixed it by rolling my rust toolchain for the project to a few days back more precisely on the latest commit date: december 5th. Seems like pear-codegen didn't like rust 1.33.0-nightly.

To roll back the toolchain for the current project folder:
`rustup toolchain install nightly-2018-12-05`
`rustup override set nightly-2018-12-05`

**Comment by igagen** [comment]
I just tried that but I'm still getting the same error. Any other steps to that I might have missed? Do I need to clean out any build artifacts?

**Comment by igagen** [comment]
Ah never mind, I was in the `/demo/client/` folder. Did the override from the root project folder and it worked like a charm. Thanks @marschr !
