### ISSUE TITLE
lorem-ipsum shouldn't snap to the nearest pixel

### ISSUE THREAD

**Issue by nadrimajstor** [pcwalton/pathfinder#11]
A noob one: looking at pathfinder and linux FF side by side
![pathfinder-vs-linuxff](https://cloud.githubusercontent.com/assets/1753467/23031268/a7dd4790-f470-11e6-8d2e-4e4d40ee7399.png)
For small-ish font size is it the subpixel rendering that makes Firefox's output looking so much better?
How much does the HDPI alleviate the difference?

**Comment by pcwalton** [comment]
The main issue here is that lorem-ipsum snaps to the nearest pixel. Fixing this requires some API and batching changes.

**Comment by pcwalton** [comment]
This is implemented now. Please feel free to open more issues for bad-looking text :)
