### ISSUE TITLE
Text rendering example

### ISSUE THREAD

**Issue by mrandri19** [pcwalton/pathfinder#143]
Having some examples which show how to render some text with pathfinder would be nice, while searching I could only find this link from an HN post: (https://github.com/pcwalton/pathfinder/blob/49408b95cb9a159a0912e38cd81a953d3e2a0ae1/examples/benchmark.rs) but it seems outdated.
I could work on a pull request if someone points to the right direction :)

**Comment by pcwalton** [comment]
I would like to implement the fillText API for canvas for this, using the `font-kit` and `skribo` crates.

**Comment by pcwalton** [comment]
Specifically, check this out: https://github.com/linebender/skribo/blob/master/examples/render.rs

To actually rasterize the glyphs, you will need to use the `font-kit` API to pull out the glyph data and convert it into paths, which you then add to a Scene.

**Comment by pcwalton** [comment]
I'm going to close this in favor of #141.
