### ISSUE TITLE
u and other letters are not rendered

### ISSUE THREAD

**Issue by est31** [pcwalton/pathfinder#16]
The letter u is not rendered.

See the screenshot:

![screenshot_20170228_232555](https://cloud.githubusercontent.com/assets/8872119/23437130/4118e9fa-fe0d-11e6-8dbf-aa161321a03c.png)

Used font: `OxygenMono-Regular.ttf` . Can be extracted from [the ubuntu package](http://archive.ubuntu.com/ubuntu/pool/universe/o/oxygen-fonts/oxygen-fonts_5.4.3.orig.tar.xz), located under `oxygen-fonts/mono-400/OxygenMono-Regular.ttf`.

My setup:
```
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.3
```

**Comment by pcwalton** [comment]
I think this may be kerning going awry

**Comment by pcwalton** [comment]
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment]
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.
