### ISSUE TITLE
Switch from using Triangle Fan primitives to Triangle List or Strip

### ISSUE THREAD

**Issue by bzm3r** [pcwalton/pathfinder#165]
PF3 uses triangle fan primitives, however modern graphics APIs (DX12 and Vulkan in particular) no longer support this primitive. Therefore, gfx-hal does not support it eitehr. PF3 switching to TriangleList would thus be helpful for a gfx-hal based PF3 renderer.

**Comment by bzm3r** [comment]
@pcwalton Will you implement this change, or should I look into doing it? I would be happy to try my hand at it, but I am not sure how complicated it will be.

**Comment by pcwalton** [comment]
I'll eventually get around to this, but feel free to take it before then.
