### ISSUE TITLE
Investigate performance of NV_path

### ISSUE THREAD

**Issue by LifeIsStrange** [pcwalton/pathfinder#166]
NV_path is maybe the most gpu optimized way for path rendering.
Chromium got a very significant improvement from it https://bugs.chromium.org/p/chromium/issues/detail?id=344330

https://www.khronos.org/registry/OpenGL/extensions/NV/NV_path_rendering.txt
Btw Bas Schouten from Mozilla was a contributor of the extension.
And Azure has an NV_path backend
https://wiki.mozilla.org/Platform/GFX/Moz2D

**Comment by pcwalton** [comment]
NV_path_rendering has batching hazards and cannot achieve the antialiasing quality that Pathfinder has. Closing.
