### ISSUE TITLE
Expose generic vector rendering API

### ISSUE THREAD

**Issue by dragostis** [pcwalton/pathfinder#17]
I saw your recent presentation, and I would be interested in maybe giving this a shot. Font parsing should also probably be hidden behind a feature.

**Comment by whmountains** [comment]
What would be required for this to be a reality?  I also might be willing to help with this if I knew what was required.

**Comment by whmountains** [comment]
What would be required for this to be a reality?  I also might be willing to help with this if @dragostis doesn't get to it first.

**Comment by pcwalton** [comment]
This is basically implemented now as part of Pathfinder 2. Further enhancements should be filed as specific issues.
