### ISSUE TITLE
No text appears on macOS 10.9.5 with Intel Iris Pro 1536 MB

### ISSUE THREAD

**Issue by jdm** [pcwalton/pathfinder#2]
Using a 2013 macbook, I see a white background when I run `cargo run --example lorem-ipsum /Library/Fonts/Arial.ttf".

**Comment by pcwalton** [comment]
@jdm Can you retry now?

**Comment by jdm** [comment]
Still blank.

**Comment by jdm** [comment]
<img width="754" alt="screen shot 2017-02-08 at 7 02 55 pm" src="https://cloud.githubusercontent.com/assets/27658/22763184/34c0b4c6-ee31-11e6-9d2d-5da35bf94030.png">

**Comment by pcwalton** [comment]
OK, I think I'll need to add some support for dumping the GPU in use.

If you get a chance, could you try downloading gfxCardStatus (http://gfx.io) and setting to "Integrated Only" and "Discrete Only" and trying to see if one of them works?

**Comment by jdm** [comment]
It works fine now, whether I'm selecting a particular card or using dynamic switching. That's very peculiar.

**Comment by pcwalton** [comment]
Yuck. Sounds like a driver bug.

**Comment by acdha** [comment]
I encountered the same output on 10.12.3 on an iMac with an NVIDIA GeForce GTX 780M 4096 MB.

**Comment by clord** [comment]
seeing the same with 2014 rMBP, NVIDIA GeForce GT 750M 2048 MB & Intel Iris Pro 1536 MB

certainly on the discrete part (external monitor attached)

**Comment by pcwalton** [comment]
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment]
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.
