### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by boustrophedon** [pcwalton/pathfinder#20]
![2017-04-20-00 38 02](https://cloud.githubusercontent.com/assets/936147/25213569/7d8bfe76-255f-11e7-8f09-4443f897e98f.png)
![2017-04-20-00 45 49](https://cloud.githubusercontent.com/assets/936147/25213725/718e0910-2560-11e7-9a8d-dd51138cbf6b.png)

[glxinfo](https://gist.github.com/boustrophedon/533468568ae0675d7c0ed570d3c91d0f)
Graphics card is an MSI Radeon RX 480. Arch Linux with kernel 4.10.8-1, mesa 17.0.2-2, amdgpu 1.3.0-1. I used rustup override nightly to compile with rustc version 1.18.0-nightly (452bf0852 2017-04-19).

I tried running the lorem-ipsum example with `cargo run --example lorem-ipsum resources/tests/nimbus-sans/NimbusSansL-Regu.ttf` and with `cargo run --example lorem-ipsum /usr/share/fonts/TTF/FreeMono.ttf` and got the pictured results. I tried a few otfs in /usr/share/fonts/OTF but they panicked.

**Comment by boustrophedon** [comment]
Some more screenshots plus the atlas.
![2017-04-25-15 34 02](https://cloud.githubusercontent.com/assets/936147/25403503/86265710-29ca-11e7-9d53-8ecff9d1f03a.png)
![2017-04-25-15 34 04](https://cloud.githubusercontent.com/assets/936147/25403506/88615e62-29ca-11e7-8a6d-3ecc680f4353.png)
![lorem-ipsum-atlas](https://cloud.githubusercontent.com/assets/936147/25403508/8c4d6a7a-29ca-11e7-9831-3af4d3967303.png)

I am willing to work on this if you can give me some pointers on where to look.

I'm also interested in figuring out how to run opengl applications headlessly for testing purposes and documenting it. It kind of looks like you just run some sort of xvfb command and fiddle around with the DISPLAY variable. For actual CI I think you'd need to install jenkins on an aws/gce gpu instance yourself.

**Comment by pcwalton** [comment]
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment]
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.
