### ISSUE TITLE
Please consider adding a LICENSE to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [pcwalton/pathfinder#23]
While the statement at the end of the README technically provides guidance, having a LICENSE file here makes your declared license visibly apparent, and permits GitHub automation to represent your project's license visually, and will avoid setting off alarms if someone forks this into gh:mozilla/* for some reason someday.

Normally I only write this issue for gh:mozilla/* repos (as an admin of said org), but since this is a Mozilla Foundation work, I felt it appropriate to register the *request* (not demand!) here as well. I'm in #github as atoll if you wish to follow up for any reason out of band, too.

**Comment by est31** [comment]
Pathfinder 1.0 originally had a license file, and the classic subdirectory still has it. It got moved out of the root directory in 93c928bf5cf11d64d2baa9840bbd80b90a2ceab1 . Seems that @pcwalton missed to add a LICENSE file to the pathfinder 2.0 code since then.
