### ISSUE TITLE
No curves rendered on Linux Nvidia 970M with official drivers

### ISSUE THREAD

**Issue by siriux** [pcwalton/pathfinder#25]
I can get the demo to work on firefox, but all the letters are only composed of straight lines, no curves rendered.

On Chromium nothing is shown at all, just the white background when the font is loaded.

Do I need to enable something on the browsers?

**Comment by pcwalton** [comment]
What font are you trying?

**Comment by siriux** [comment]
The Nimbus provided in the repo.

**Comment by siriux** [comment]
I've tested with ECAA and it's worst.

This is with No AA in firefox:

![image](https://user-images.githubusercontent.com/715386/29747895-1e0547c2-8b09-11e7-826e-b4f9452237e3.png)

This is with ECAA in firefox:

![image](https://user-images.githubusercontent.com/715386/29747900-445b5c40-8b09-11e7-8e90-1cc9fd4a905b.png)

In chromium there just a white screen, no text.

**Comment by pcwalton** [comment]
Does anything appear in the console? I suspect this is a driver issue, although I cannot reproduce on NVIDIA on Windows.

**Comment by siriux** [comment]
In firefox, for the "No AA" case I get:

```
Error: Bootstrap dropdown require Popper.js (https://popper.js.org)  bootstrap.js:1414:11
Error: WebGL warning: texSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.  text.js:9577:13
Error: WebGL warning: texSubImage2D: This operation requires zeroing texture data. This is slow.  text.js:9577:13
Error: WebGL warning: texSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.  text.js:9577:13
Error: WebGL warning: texSubImage2D: This operation requires zeroing texture data. This is slow.  text.js:9577:13

```
If I change to ECAA I get the same error again.

**Comment by siriux** [comment]
This is what I get on chromium:

```
bootstrap.js:1414 Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)
    at bootstrap.js:1414
    at bootstrap.js:1823
    at bootstrap.js:3831
(anonymous) @ bootstrap.js:1414
(anonymous) @ bootstrap.js:1823
(anonymous) @ bootstrap.js:3831
text.js:9912 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
localhost/:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
```

**Comment by pcwalton** [comment]
OK, so no unexpected errors. This feels like a silent driver issue.

**Comment by siriux** [comment]
Something I've noticed is that in non-ECAA modes the curved parts are rendered all on top of each other at the end of a sentence ( or is it in small symbols like ,.- ?):

![image](https://user-images.githubusercontent.com/715386/30469587-3b65163e-99f1-11e7-9bda-f9afaa9ec83d.png)

We can see this even better on the benchmark (but here is at the beginning):

![image](https://user-images.githubusercontent.com/715386/30469688-c02e070e-99f1-11e7-85df-a1b19c38e699.png)

It seems like a positioning problem, and it might be the same bug as the ECAA error, but here it could be easier to spot.

**Comment by pcwalton** [comment]
Could you try ECAA now if you get a chance?

My theory is that the buffer textures are getting weirdly messed up with your driver.

**Comment by siriux** [comment]
Now nothing is working, but it seems a different bug that happens before: 

In Firefox I get:

```
Error: WebGL warning: linkProgram: Must have a compiled vertex shader attached. shader-loader.ts:160:8
TypeError: layout is undefined[Learn More]  text-demo.ts:481:8
Error: WebGL warning: texSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.  buffer-texture.ts:60:12
Error: WebGL warning: texSubImage2D: This operation requires zeroing texture data. This is slow.  buffer-texture.ts:60:12
Error: WebGL warning: texSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.  buffer-texture.ts:60:12
Error: WebGL warning: texSubImage2D: This operation requires zeroing texture data. This is slow.  buffer-texture.ts:60:12
Error: WebGL warning: useProgram: Program has not been successfully linked.  ecaa-strategy.ts:204:8
Error: WebGL warning: useProgram: Program has not been successfully linked. ecaa-strategy.ts:257:12
Error: WebGL warning: useProgram: Program has not been successfully linked. ecaa-strategy.ts:313:12
Error: WebGL warning: useProgram: Program has not been successfully linked.  ecaa-strategy.ts:364:8
Error: WebGL warning: texSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.  buffer-texture.ts:60:12
Error: WebGL warning: texSubImage2D: This operation requires zeroing texture data. This is slow.  buffer-texture.ts:60:12
Error: WebGL warning: useProgram: Program has not been successfully linked.  ecaa-strategy.ts:391:8
Error: WebGL warning: drawElementsInstanced: The current program is not linked.  ecaa-strategy.ts:394:8
Error: WebGL warning: useProgram: Program has not been successfully linked.  ecaa-strategy.ts:430:8
Error: WebGL warning: drawElementsInstanced: The current program is not linked. ecaa-strategy.ts:441:12
Error: WebGL warning: useProgram: Program has not been successfully linked.  ecaa-strategy.ts:455:8
Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings)
```

And in chromium:

```
Uncaught (in promise) TypeError: Cannot read property 'layoutRuns' of undefined
    at TextDemoView.layoutText (text-demo.js:41133)
    at TextDemoView.setAntialiasingOptions (text-demo.js:41032)
    at view.then.view (text-demo.js:32046)
    at <anonymous>
```

**Comment by siriux** [comment]
I tested on an old iMac early 2009 using chrome and it works perfectly, and the layout error is also present, so that's not the problem.

**Comment by siriux** [comment]
The situation has improved after removing the requirement for multiple targets (but it might be something else).

Now, on Firefox is able to render the SVG and 3D demos, with some errors. The text demo still gives a white screen. On Chrome I still get a white screen in all cases.

On the XCAA the anti aliasing is not working and there are other errors (also present in AA None):
 
![image](https://user-images.githubusercontent.com/715386/31860332-a462aa36-b718-11e7-920d-5509a50076af.png)

and in detail:

![image](https://user-images.githubusercontent.com/715386/31860340-bcd1f3ec-b718-11e7-89af-b16248908f03.png)

I get something similar using AA None that maybe gives hints to the other problems:

![image](https://user-images.githubusercontent.com/715386/31860347-f169594c-b718-11e7-8493-7f13d0a630c6.png)

Finally, 3D with AA None:

![image](https://user-images.githubusercontent.com/715386/31860375-223b9ada-b719-11e7-867c-dd18cf8ad1e0.png)

**Comment by pcwalton** [comment]
No longer using WebGL in Pathfinder 3, so I don't think this is relevant any longer.
