### ISSUE TITLE
client/js directory seems to be missing

### ISSUE THREAD

**Issue by est31** [pcwalton/pathfinder#27]
When I cd to demo/server and then cargo run it and then visit it in the browser, the browser console gives me a couple of 404's for stuff in the js directory. Maybe its not checked into git?

**Comment by lqd** [comment]
The js probably needs to be built first, by compiling the client typescript code with npm+webpack :)

**Comment by siriux** [comment]
You can build it with `npm run build` you might also need to install the modules first with `npm install`. That worked for me.

**Comment by siriux** [comment]
I forgot to say that you need to execute those commands inside the demo/client directory.

**Comment by est31** [comment]
@lqd @siriux thanks for the info! I guess I'm folding this into #26 then.
