### ISSUE TITLE
expose more data from partitioner

### ISSUE THREAD

**Issue by daiheitan** [pcwalton/pathfinder#29]
Current partitioner API is not easy for situation like caching. As it clears buffers on every `.partition()` call, an extra copy is needed to store the old partition data. An API to directly output the buffers instead of offering slices would be better.

**Comment by pcwalton** [comment]
Do you mean you want to able to store multiple paths' points in the same set of buffers instead of having to copy them out?

**Comment by daiheitan** [comment]
I thought it would be better to return the old data using something like `split_off(0)`, instead of just clearing it. Anyway copying is not too bad as a choice.

**Comment by pcwalton** [comment]
The new `MeshLibrary` API lets you reduce copying, as requested.

**Comment by daiheitan** [comment]
Thanks!
