### ISSUE TITLE
Replace the ECAA bounding box with a minimum area bounding trapezoid

### ISSUE THREAD

**Issue by pcwalton** [pcwalton/pathfinder#33]
This might be helpful: https://mathoverflow.net/questions/11580/minimum-area-bounding-quadrilateral-algorithm

cc @trishume

**Comment by pcwalton** [comment]
Some preliminary back-of-the-envelope numbers suggests that this may not have much of an impact on performance.

**Comment by trishume** [comment]
Interesting, why is that? Is discarding the fragments just really fast, even in the worst case where large diagonal lines cover the screen so around 2x the number of fragments are shaded as a bounding trapezoid would shade?

**Comment by pcwalton** [comment]
I assume it's because the fragment shader early outs if the line doesn't pass through the pixel.
