### ISSUE TITLE
Do the algorithms behind ECAA rely on loop-blinn patents?

### ISSUE THREAD

**Issue by siriux** [pcwalton/pathfinder#34]
I see that when no antialiasing is used (or with SSAA) the loop-blinn algorithm is used (at least a few weeks ago). And this algorithm, as far as I know that is not much, is covered under some patents.

Is the ECAA algorithm based on this, or is a completely new idea and therefore not covered by these patents (as far a you know, of course).

And also, do you plan to write a post about the underlying algorithm as you did for pathfinder1? It seems pretty amazing that you managed to get this to work on opengl 3.0+ !!

Thanks a lot for your great work, this can enable a great deal of things that weren't possible before.

**Comment by pcwalton** [comment]
I can't answer specifically about patents, other than to say that Pathfinder is designed to be free of known IP concerns.

ECAA is not a Loop-Blinn-derived algorithm. The techniques behind ECAA are my original research, though based on Pathfinder 1, which is itself based on font-rs, which is based on libart...

I plan to write up a description of the techniques.

**Comment by pcwalton** [comment]
Going to go ahead and close this. Thanks for your interest and the kind words :)

**Comment by siriux** [comment]
Thanks for your quick answer.
