### ISSUE TITLE
libots fails to compile

### ISSUE THREAD

**Issue by whmountains** [pcwalton/pathfinder#36]
Running this command:

```shell
cargo run --release
```
Gives me this error:

```
CMake Error at CMakeLists.txt:119 (add_library):
  Cannot find source file:

    ots/third_party/woff2/src/buffer.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "woff2".
CMake Error: CMake can not determine linker language for target: woff2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /Users/mmc/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.26/src/lib.rs:599:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

## Versions

* MacOS: 10.13
* `rustc`: 1.22.0-nightly (7778906be 2017-10-14)
* `cargo`: 0.23.0-nightly (e447ac7e9 2017-09-27)

This seems to be related: https://github.com/servo/fontsan/issues/21

**Comment by pcwalton** [comment]
Weird.

**Comment by whmountains** [comment]
I was able to get it working by cloning fontsan manually, running `git submodule update --init --recursive`, and then modifying Cargo.toml to point it.

My understanding of git submodules and how cargo handles them is rather limited.  @pcwalton does any of this ring a bell?

**Comment by whmountains** [comment]
According to https://github.com/servo/servo/issues/13253#issuecomment-268873584, it's been fixed for new installs.  That thread also has instructions for un-breaking an existing installation.
