### ISSUE TITLE
No text renders with gamma correction enabled

### ISSUE THREAD

**Issue by rpjohnst** [pcwalton/pathfinder#48]
In the text demo, no text shows up without disabling gamma correction. The other settings don't seem to have an effect on the problem. The render time is close to what it is when text *is* visible.

* Firefox 56.0.2 (64-bit)
* Windows 10 Fall Creators Update
* Intel HD 530, latest drivers (15.60.0.4849 according to the site; 23.20.16.4849 according to Task Manager)

No errors in the debug console, only the `texSubImage2D` warnings about zeroing texture data.

**Comment by Bobo1239** [comment]
Welp, on my machine (Windows 10; AMD RX 480; Radeon 17.7.2) I have the same issue most of the time but sometimes the text does show up...
At least I'm getting a hopefully helpful error message when it doesn't:
![chrome_2017-11-12_16-31-03](https://user-images.githubusercontent.com/2302947/32700540-e9e131e0-c7c6-11e7-99fb-df1e2b90cab4.png)

**Comment by pcwalton** [comment]
Can you try now? I believe I've fixed a race between initial render and gamma LUT loading.

**Comment by rpjohnst** [comment]
Surprisingly I just ran it without that commit for unrelated reasons and it was working, so I'm not sure I'd be able to tell if the fixed worked.

The changes since I reported it were pulling to commit 529a3eae2317872825a8c7c11625a6c5ff731a2a, and updating to Firefox 57. I can try reinstalling 56 to see if that re-breaks it, if you think that would be valuable.

**Comment by pcwalton** [comment]
The race I fixed caused intermittent failures, so that would be consistent with your failure being the result of that problem. I'll go ahead and close this. Feel free to reopen if you run into this problem again.
