### ISSUE TITLE
Text demo only renders at 45fps due to slow per-frame layout

### ISSUE THREAD

**Issue by trishume** [pcwalton/pathfinder#49]
I noticed that while the SVG and 3D demos render at 60fps and almost entirely on the GPU, the text demo only runs at 45fps and spins up my laptop fans doing a bunch of CPU work every frame.

Looking at the profile and code it looks like layout is being done every frame. It seems that this is currently required for stem darkening and hinting to work, but is done even when both of those features are disabled. I can't see any obvious hotspots in the profile, but given that the amount of text being rendered is pretty small compared to most web pages, I imagine this will have to get better if you want to fulfill your ambitions.

Why is it that layout is done on the CPU every frame? I thought I remember seeing something about you doing stem darkening on the GPU. I imagine you have some optimizations in mind and just haven't got around to implementing them yet.

I'm super impressed by the current state of the demo though. The quality is amazing, the other two demos are crazy fast, and the GPU times on the text demo are still great.

<img width="1884" alt="screen shot 2017-11-11 at 9 14 44 pm" src="https://user-images.githubusercontent.com/887610/32695335-baa6737c-c726-11e7-8b52-396b2b1c9326.png">

**Comment by pcwalton** [comment]
The problem is that we have to lay out the atlas from frame to frame as glyphs enter and exit the view (because we don't render glyphs that are off screen). That means that we have to keep modifying uvs every frame, since glyphs may be at a different atlas rect each frame. This is the same kind of thing that WebRender has to do. Unfortunately, I have to do it in JavaScript, which is why it's slow…

There is probably a simpler solution that will work.

**Comment by trishume** [comment]
Interesting. Especially since the amount of text in the demo is a pretty small amount I would hope WebRender would be able to process in less than a millisecond. I know Javascript is slower than Rust but over 10x isn't what I would have expected for a modern JIT, does Webrender do something smarter that Pathfinder could do as well maybe? Or is it maybe something that making the JS use more linear typed arrays could help?

Although I imagine that CPU performance of the JS demo isn't considered super important since it's a demo, and while GPU performance is reflective of GPU performance in a real system, any real system would have a different CPU implementation.

**Comment by LifeIsStrange** [comment]
Has the situation evolved now ?

**Comment by pcwalton** [comment]
No longer relevant with Pathfinder 3
