### ISSUE TITLE
MacBook Pro 2014 fails to render XCAA text (Firefox+Chrome)

### ISSUE THREAD

**Issue by mmastrac** [pcwalton/pathfinder#51]
I originally filed #2 for Pathfinder 1, but it appears that Pathfinder 2 is just as broken on my 2014 Macbook Pro.

I've tested under both Firefox and Chrome and neither can successfully render glyphs in XCAA mode, but work just fine in 4xSSAA.

System

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz

GPUs:

1

  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0d26
  Revision ID:	0x0008
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3

2

  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2 GB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3

<img width="1207" alt="screen shot 2017-11-27 at 10 34 10 am" src="https://user-images.githubusercontent.com/512240/33280341-f685d06a-d35e-11e7-8721-4ff455004354.png">
<img width="1170" alt="screen shot 2017-11-27 at 10 34 19 am" src="https://user-images.githubusercontent.com/512240/33280342-f69abdcc-d35e-11e7-8332-5dd03feb5786.png">

**Comment by mmastrac** [comment]
I took some screenshots of larger busted glyphs to illustrate the problem (and hopefully suggest what the failure mode might be):

<img width="177" alt="screen shot 2017-11-27 at 10 47 34 am" src="https://user-images.githubusercontent.com/512240/33280808-8fee609a-d360-11e7-93c6-94af51125494.png">
<img width="152" alt="screen shot 2017-11-27 at 10 47 46 am" src="https://user-images.githubusercontent.com/512240/33280809-90079448-d360-11e7-8d0c-9155c8661619.png">
<img width="174" alt="screen shot 2017-11-27 at 10 47 53 am" src="https://user-images.githubusercontent.com/512240/33280811-901ae502-d360-11e7-953a-0b0140f6f6c6.png">
<img width="105" alt="screen shot 2017-11-27 at 10 48 00 am" src="https://user-images.githubusercontent.com/512240/33280813-902e8652-d360-11e7-94c9-ed1b23da2de7.png">
<img width="155" alt="screen shot 2017-11-27 at 10 48 07 am" src="https://user-images.githubusercontent.com/512240/33280814-9044502c-d360-11e7-9e44-2b49fc93b8c3.png">

**Comment by mmastrac** [comment]
Example of transition from font size 72 to font size 73, using Open Sans:

O

<img width="66" alt="screen shot 2017-11-27 at 10 52 57 am" src="https://user-images.githubusercontent.com/512240/33281074-3f5c5064-d361-11e7-9e0a-0f0ef2d1e636.png">
<img width="64" alt="screen shot 2017-11-27 at 10 53 00 am" src="https://user-images.githubusercontent.com/512240/33281075-3f70fd66-d361-11e7-9c3a-7f492c678784.png">

B

<img width="63" alt="screen shot 2017-11-27 at 10 53 07 am" src="https://user-images.githubusercontent.com/512240/33281076-3f83e552-d361-11e7-9ff5-3bd62cf71ee2.png">
<img width="53" alt="screen shot 2017-11-27 at 10 53 10 am" src="https://user-images.githubusercontent.com/512240/33281077-3f995a86-d361-11e7-96f4-d5211ff2b045.png">

1

<img width="45" alt="screen shot 2017-11-27 at 10 53 17 am" src="https://user-images.githubusercontent.com/512240/33281078-3faeb570-d361-11e7-9fc2-5d4aeea8e1e3.png">
<img width="44" alt="screen shot 2017-11-27 at 10 53 20 am" src="https://user-images.githubusercontent.com/512240/33281079-3fdb6d9a-d361-11e7-9004-b67cf5fc203c.png">

X

<img width="63" alt="screen shot 2017-11-27 at 10 53 25 am" src="https://user-images.githubusercontent.com/512240/33281080-3ff0f246-d361-11e7-9114-66bfc8151806.png">
<img width="60" alt="screen shot 2017-11-27 at 10 53 28 am" src="https://user-images.githubusercontent.com/512240/33281081-4003413a-d361-11e7-87ac-e46323398a25.png">

**Comment by trishume** [comment]
I also have a 2014 rMBP. I've experienced artifacts, although I don't remember if they were like these, at varying times. I would try to replicate but I actually can't build Pathfinder right now because fontsan depends on an old `miniz-sys` that doesn't compile on my machine with the error `could not find native static library 'miniz', perhaps an -L flag is missing?`.

**Comment by mmastrac** [comment]
I fiddled with some of the shaders to no avail but I strongly suspect a driver bug in `computeCoverage`. I tried rearranging some of the code to remove conditionals, but nothing really helped.

Changing a2x to `p0X.x + dPX.x` when `slopeIsNegative` is false moves the artifacts in an interesting way that suggests that this method could be the the culprit:

```
     } else {
-        a2x = p0X.x;
+        a2x = p0X.x + dPX.x;
         a0 = p1;
         a1 = p0;
     }
```

Before that change:

<img width="177" alt="screen shot 2017-11-27 at 10 47 34 am" src="https://user-images.githubusercontent.com/512240/33288385-50c4afc8-d379-11e7-8adf-2b6d9120dd73.png">

After that change:

<img width="180" alt="screen shot 2017-11-27 at 1 45 45 pm" src="https://user-images.githubusercontent.com/512240/33288384-50afcec8-d379-11e7-94d6-c738058da82e.png">

**Comment by pcwalton** [comment]
If anyone can bisect this change down, that would be very helpful. (I can't reproduce, obviously…)

**Comment by trishume** [comment]
I bisected it and found `7bd3a481105fa9f20bafbcfba6b9ed1cc1e7f573` is the first bad commit for the new artifact. It's parent `6d85cb338243a5f637aa829c45ef9a83927979b1` works. There also was an old artifact that I ended up bisecting in order to find a good commit for the new bisect, so that info is in the log below as well.

```
8897145f54f6ca5c88983cd362f429c2ae29460b old artifact
77fa297380799e467f293d36ad8208334dbc159a old artifact
092b46e056dd17360078d52c7d60e28bc42cd4d2 good
81787f4750031976056b44819c0cdf0cd4e4e8ef old artifact
6a7c013e617cc0287f17630a6c30aeeccb0f9192 good
314185684cb5995c26bb0b4a33878ee50e9e648c old artifact
c2368bb71edcc9f806ed7b2002841f4737c5c5fb good
3352f869f0a921e1c3e942a8dae2cf5cd39a3e43 good
314185684cb5995c26bb0b4a33878ee50e9e648c is the first bad commit for the old artifact

2e90b3bce8db697052a1f17da670ebe76f34f874 no text at all
86df78f939c944df9da1f8c282dd8d3679947f4f good
5a1e4d4e606a2ec6617bdcfc0735133d966856d9 good
99c7e685e785b0a38ad2d30bd0650f3a76bbc943 good
7bd3a481105fa9f20bafbcfba6b9ed1cc1e7f573 is the first bad commit for the new artifact

d65bfb7fb20fffba15aa5203c26caa6d3794cd2e old artifact
86df78f939c944df9da1f8c282dd8d3679947f4f good
5a1e4d4e606a2ec6617bdcfc0735133d966856d9 good
99c7e685e785b0a38ad2d30bd0650f3a76bbc943 good
6d85cb338243a5f637aa829c45ef9a83927979b1 good
```

**Comment by trishume** [comment]
I did some debugging and the artifacts are the exact same as if I remove the early return in `computeCoverage` (here https://github.com/pcwalton/pathfinder/blob/7bd3a481105fa9f20bafbcfba6b9ed1cc1e7f573/shaders/gles2/common.inc.glsl#L263) and run it on my Iris Pro, which usually works. So it seems somehow the Apple Nvidia GPU shader compiler isn't compiling that early return properly.

**Comment by mmastrac** [comment]
Confirmed fixed. Looks beautiful.

For posterity, the GPU/CUDA version on my machine:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/512240/33645133-802ddd1e-da06-11e7-969a-5031546c46f7.png">
