### ISSUE TITLE
Core i7 3770 (Ivy Bridge) + Linux + Firefox MCAA fails

### ISSUE THREAD

**Issue by doppioandante** [pcwalton/pathfinder#52]
On the text demo, zooming too much causes the text to appear like this:
![text demo](https://i.imgur.com/ug1EjRP.png)
Changing options doesn't make much of a difference (sometimes the artifacts change), but using a different antialiasing solves this.

If I activate subpixel-AA the rendering time jumps to 90-120ms, but only after the same level of zoom where the bad rendering shows up.
I'm using linux with the integrated GPU of the Core i7 3770 (Ivy Bridge).
The browser is Firefox 58.0b6

relevant glxinfo:
```
client glx vendor string: Mesa Project and SGI
    Device: Mesa DRI Intel(R) Ivybridge Desktop  (0x162)
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Desktop 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.2.2 - padoka PPA
OpenGL version string: 3.0 Mesa 17.2.2 - padoka PPA
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.2 - padoka PPA
```

**Comment by pcwalton** [comment]
Suspect driver bug.

**Comment by doppioandante** [comment]
I should try this on Windows, unfortunately I have no rust dev env there.

**Comment by doppioandante** [comment]
Good news, it works now. It was commit 7e0d003a95695e00d21c41107c707fb7c4ddb0aa, so I think that the shader bug is not triggered anymore after that refactoring.

**Comment by pcwalton** [comment]
Great, thanks for testing!
