### ISSUE TITLE
Chromium doesn't show anything on linux

### ISSUE THREAD

**Issue by doppioandante** [pcwalton/pathfinder#53]
Chromium Version: `62.0.3202.94`
I couldn't find a similar issue, maybe it's already known.
Every demo is blank, I get the following errors in the console:
```
Uncaught (in promise) TypeError: Cannot read property 'createQueryEXT' of null
    at TextDemoView.initContext (text-demo.js:23417)
    at new DemoView (text-demo.js:23334)
    at new TextDemoView (text-demo.js:42460)
    at TextDemoController.createView (text-demo.js:42357)
    at view.Promise.all.then.assets (text-demo.js:32508)
    at <anonymous>
```
```
text-demo.js:23392 Uncaught TypeError: Cannot read property 'canvasResized' of undefined
    at TextDemoView.resized (text-demo.js:23392)
    at TextDemoView.resizeToFit (text-demo.js:23320)
    at PathfinderView.window.addEventListener (text-demo.js:23260)
```
```
text-demo.js:23379 Uncaught TypeError: Cannot read property 'meshesAttached' of undefined
    at TextDemoView.redraw (text-demo.js:23379)
    at window.requestAnimationFrame (text-demo.js:23266)
```

**Comment by dylanede** [comment]
I'm getting the "createQueryEXT" errors on Chrome 62 on Windows 7 as well, and every demo is blank.

**Comment by Darkspirit** [comment]
Chromium 62.0.3202.89 @ Debian Testing (KDE, Radeon RX480):
It's just working fine. (Am I doing something wrong?)

![screenshot_20171208_032017](https://user-images.githubusercontent.com/17962859/33748067-c8973ca0-dbc6-11e7-9508-336cbd17d802.png)

**Comment by dylanede** [comment]
Further investigation on my part suggests a driver bug. I get a similar problem in Firefox. The demos *very* occasionally work. If I instead switch ANGLE on Firefox to use the reference software rasteriser (WARP) in DirectX, the demos work reliably, and the performance isn't actually that bad.

**Comment by doppioandante** [comment]
Works now on my system, it would be hard to track what made it work...
The left whiskers on the tiger SVG don't render in chrome (or maybe render white without a border?) but I don't have the time to file a issue for that, sorry :(.
