### ISSUE TITLE
Link error on macOS 10.12.6

### ISSUE THREAD

**Issue by mindbrix** [pcwalton/pathfinder#56]
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/pathfinder_server-d81cfa61efd7b6db.pathfinder_server0.rcgu.o" "-o" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/pathfinder_server-d81cfa61efd7b6db" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/pathfinder_server-d81cfa61efd7b6db.crate.allocator.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps" "-L" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/build/fontsan-72fd1c942a3f2fa9/out/lib" "-L" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/build/miniz-sys-64ca519ecee376a4/out" "-L" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/build/ring-7dfcc1e9a995e56d/out" "-L" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/librocket_contrib-50f6cc556a05d100.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/librocket-c687ad2776b3eba0.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libcookie-96a656274a53deda.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libpear-959f47670bc30146.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libstate-dee99d4d108de679.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libisatty-886a79c03dfa7b12.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libimage-d34a7ac826db8776.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libgif-e2e5b125a6b77ca7.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liblzw-4a755344faf49a52.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libpathfinder_font_renderer-43b36ba08d004703.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libcore_text-20bcaa6aaf827fd3.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libapp_units-d54ebfcf596ba1d6.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libtoml-3c80b1b386b7e329.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libordermap-06cb6dba1facb08f.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libpng-81e04733ba5d90ba.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libinflate-102de0c06e0a1b46.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libnum_iter-4dab621078e5df00.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/librustc_serialize-a889a4fe3a7dbe63.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libsmallvec-a808ef5d69ec0b43.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libfontsan-11577004c92f8e88.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libminiz_sys-9ac7185d460f891e.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libenum_primitive-95af202657897c7f.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libjpeg_decoder-3ac8f0b748522f0d.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/librayon-fca4aa22d72785c8.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/librayon_core-5250b944c2d358d9.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/librand-42d60fa77ae4023d.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libcoco-63db7513d1dee27f.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liblru_cache-0470ac7203f498be.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liblinked_hash_map-74322f2fc732fbb3.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libcore_graphics-204af4f0a9fbf11d.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libforeign_types-d74f661f34d1684d.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libbitflags-fb9a35f0935039a2.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libcore_foundation-88be1239c0fca397.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libcore_foundation_sys-36a1191d5d49ad78.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libpathfinder_partitioner-4485704a257d1a69.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libpathfinder_path_utils-be4fc8cf9bf9d4a9.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libbit_vec-30aa1d07dfe6813f.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libbincode-7953a2e0f73f2b40.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libhyper-22ac0d1694dad5bc.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libmime-9b254f7900017ed9.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libtraitobject-108c02eb9919f1ae.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libnum_cpus-860dc29147df84b4.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libhttparse-dd835a0c0660ae20.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libunicase-424fa30f5dfce43b.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liburl-81c648a08d15e474.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libpercent_encoding-1d7caa3fff43b039.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libidna-d8410879a6b3a33e.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libtime-edfe3e3dc1d62e63.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libbase64-a5b58026b4a182bf.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libunicode_normalization-5554160ea15a56ed.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libenv_logger-854b26903ddb5393.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libregex-6ad1442de2a59485.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libregex_syntax-46e9017375f46c02.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libaho_corasick-ae6f749088280399.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libmemchr-e2311e38eeb1ece1.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liblanguage_tags-f450c4c6019e503f.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libthread_local-dc7d08b90c7a96a6.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liblazy_static-12fee8d0b016dbdc.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libunreachable-2588997982ba550f.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libvoid-6d58bea43c9f4258.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libeuclid-a74510d706dba974.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liblog-86cd8093cf57a34e.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libnum_rational-a05bb3e025e89b22.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libdeflate-f5c9944630e87fb7.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libbyteorder-2d6912b733347e9f.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libscopeguard-5c47a00daea80856.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libscoped_threadpool-804789269f798f3b.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libfreetype_sys-bb92a533be03add1.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libyansi-279006fdfa4f8728.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libheapsize-ed43fb22de3698a7.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libunicode_bidi-941bcf27ebc859b8.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libmatches-cc6598cb83827685.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libsafemem-d657b6868445abad.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libtypeable-d1b4be1f70cb1c5b.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libring-bd4cdac761666a11.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libuntrusted-a50e3276b397c9bd.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/liblibc-c70a44633b9f30ed.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libutf8_ranges-6460f1bd9c2078a7.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libserde_json-0cee4a0a4369a078.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libdtoa-926e433c78d547b3.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libitoa-32cc207585aac845.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libserde-b599bb20eb67327a.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libnum_integer-66320512b287c4c7.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libnum_traits-2d49ea83b07a584c.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libadler32-b3131c1060b7a904.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libeither-527bcc5ab71684bd.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libcolor_quant-055a54b9e6af76eb.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libarrayvec-c5c41ddda4719ac2.rlib" "/Users/nigelbarber/Documents/github/pathfinder/demo/server/target/release/deps/libnodrop-4614bc1ccbed7893.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-37507bc42dbe9769.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-1ce580742eee3c59.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-e2f3a8bc2c37efd7.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-cf7427b7cf136f9f.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_system-2ae91ee530952540.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-411dd041b417f2dc.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-b9404d2d88ffe119.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_unicode-bfc8f9db37aaf43c.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librand-ddc29881ce534568.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-ecc3b9887f78fe76.rlib" "/Users/nigelbarber/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-3f172fbe1067a0ac.rlib" "-framework" "ApplicationServices" "-l" "c++" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreFoundation" "-l" "freetype" "-framework" "Security" "-l" "System" "-l" "resolv" "-l" "pthread" "-l" "c" "-l" "m"
  = note: ld: library not found for -lfreetype
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: Could not compile `pathfinder_server`.

**Comment by rpjohnst** [comment]
This also happens on Windows. It looks like the reference tests just haven't been implemented for every platform yet.

**Comment by pcwalton** [comment]
The solution is going to be to make these dependencies optional.

**Comment by jfirebaugh** [comment]
I tried to workaround the first linker error by running `brew install freetype`, which worked. The next error was:

```
   Compiling pathfinder_server v0.1.0 (file:///Users/john/Development/pathfinder/demo/server)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/john/Development/pathfinder/target/release/deps/pathfinder_server-0affd907f1298449.pathfinder_server0.rcgu.o" "-o" "/Users/john/Development/pathfinder/target/release/deps/pathfinder_server-0affd907f1298449" "/Users/john/Development/pathfinder/target/release/deps/pathfinder_server-0affd907f1298449.crate.allocator.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/john/Development/pathfinder/target/release/deps" "-L" "/Users/john/Development/pathfinder/target/release/build/fontsan-8332d689e164a3ce/out/lib" "-L" "/Users/john/Development/pathfinder/target/release/build/miniz-sys-64f8c78be9d5c223/out" "-L" "/Users/john/Development/pathfinder/target/release/build/ring-37831b212a4a128b/out" "-L" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/john/Development/pathfinder/target/release/deps/libpathfinder_font_renderer-171731fcb34ff7d2.rlib" "/Users/john/Development/pathfinder/target/release/deps/libpathfinder_partitioner-4819ba071f819e3a.rlib" "/Users/john/Development/pathfinder/target/release/deps/librocket_contrib-05b7941375dd97a6.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblru_cache-c2d087eb3806ef11.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcore_text-813c7e1de06b29f7.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcore_graphics-513818f00c6aeac8.rlib" "/Users/john/Development/pathfinder/target/release/deps/librocket-927d46aa0edcd609.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcookie-9e2352d302999c79.rlib" "/Users/john/Development/pathfinder/target/release/deps/libyansi-08bb539a71276462.rlib" "/Users/john/Development/pathfinder/target/release/deps/libordermap-1d40823b38506b90.rlib" "/Users/john/Development/pathfinder/target/release/deps/libforeign_types-5d369fcd2781edc4.rlib" "/Users/john/Development/pathfinder/target/release/deps/libtoml-6a80fe19ca8c6f97.rlib" "/Users/john/Development/pathfinder/target/release/deps/libimage-a5ee286e2607ccf1.rlib" "/Users/john/Development/pathfinder/target/release/deps/libjpeg_decoder-eb5b2836b13aa4a0.rlib" "/Users/john/Development/pathfinder/target/release/deps/libenum_primitive-59d4b69e0f3dfcaf.rlib" "/Users/john/Development/pathfinder/target/release/deps/libpathfinder_path_utils-61745e0fcb59ad8c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libeuclid-66a032686714571d.rlib" "/Users/john/Development/pathfinder/target/release/deps/libbincode-8b46ea86b234d535.rlib" "/Users/john/Development/pathfinder/target/release/deps/libmemchr-6af3c4ac51fcf38d.rlib" "/Users/john/Development/pathfinder/target/release/deps/libpng-38d50fe0790dcae0.rlib" "/Users/john/Development/pathfinder/target/release/deps/libgif-e58f9252a0bb5fff.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcolor_quant-36048b615dc7ad4f.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcore_foundation-59107bd80d8dc458.rlib" "/Users/john/Development/pathfinder/target/release/deps/libhyper-e64921846f703b4f.rlib" "/Users/john/Development/pathfinder/target/release/deps/libtypeable-99428ecab17ad7cc.rlib" "/Users/john/Development/pathfinder/target/release/deps/libhttparse-8e14b8eee00829f3.rlib" "/Users/john/Development/pathfinder/target/release/deps/liburl-612d9b83823cfed1.rlib" "/Users/john/Development/pathfinder/target/release/deps/libpercent_encoding-1c2ba1d4e5a3c94f.rlib" "/Users/john/Development/pathfinder/target/release/deps/libidna-d95234eacafa8f26.rlib" "/Users/john/Development/pathfinder/target/release/deps/libunicode_normalization-1308d1554ab9b60b.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblanguage_tags-b019c164c0d45a78.rlib" "/Users/john/Development/pathfinder/target/release/deps/libfontsan-48c0c3180e26913c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libserde_json-8670b7af9ba9ea0d.rlib" "/Users/john/Development/pathfinder/target/release/deps/libdtoa-ba41080e3ecee786.rlib" "/Users/john/Development/pathfinder/target/release/deps/librayon-1669b427f45a88c7.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblinked_hash_map-2790058b097e1641.rlib" "/Users/john/Development/pathfinder/target/release/deps/libapp_units-7053af56240ed2d4.rlib" "/Users/john/Development/pathfinder/target/release/deps/libserde-acfcad1030b48816.rlib" "/Users/john/Development/pathfinder/target/release/deps/libheapsize-a208484ffd18e8ac.rlib" "/Users/john/Development/pathfinder/target/release/deps/libfreetype_sys-869feb125fffea75.rlib" "/Users/john/Development/pathfinder/target/release/deps/libunicode_bidi-5c13688db4fe8807.rlib" "/Users/john/Development/pathfinder/target/release/deps/libring-9b2e9f14801c886a.rlib" "/Users/john/Development/pathfinder/target/release/deps/libuntrusted-7ae7e2da1b726854.rlib" "/Users/john/Development/pathfinder/target/release/deps/libnum_rational-1a299c354863057f.rlib" "/Users/john/Development/pathfinder/target/release/deps/libbase64-5245222c4e8624cb.rlib" "/Users/john/Development/pathfinder/target/release/deps/libsafemem-2971441ba0d714b4.rlib" "/Users/john/Development/pathfinder/target/release/deps/libpear-15859c3aca8958d8.rlib" "/Users/john/Development/pathfinder/target/release/deps/libenv_logger-553878e4d6ef666e.rlib" "/Users/john/Development/pathfinder/target/release/deps/libregex-4eb04d3f3f787337.rlib" "/Users/john/Development/pathfinder/target/release/deps/libregex_syntax-1225b3dc300b9573.rlib" "/Users/john/Development/pathfinder/target/release/deps/libthread_local-80ce62d2ff2bf6f2.rlib" "/Users/john/Development/pathfinder/target/release/deps/libunreachable-af12c8bcba25d986.rlib" "/Users/john/Development/pathfinder/target/release/deps/libvoid-b0a6754bef1fd912.rlib" "/Users/john/Development/pathfinder/target/release/deps/libtraitobject-e4e5a9659cde9924.rlib" "/Users/john/Development/pathfinder/target/release/deps/libutf8_ranges-149130b3a31b9701.rlib" "/Users/john/Development/pathfinder/target/release/deps/libisatty-7a80872e842d2df2.rlib" "/Users/john/Development/pathfinder/target/release/deps/libdeflate-88c3f2d48906000c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libbyteorder-13d2227dc4958863.rlib" "/Users/john/Development/pathfinder/target/release/deps/libscoped_threadpool-49b4a7e7fc418156.rlib" "/Users/john/Development/pathfinder/target/release/deps/libforeign_types_shared-a87dda4311f8b07a.rlib" "/Users/john/Development/pathfinder/target/release/deps/libmatches-5b82b86b4a1fb5af.rlib" "/Users/john/Development/pathfinder/target/release/deps/libaho_corasick-cf6fc4d1fd4094ba.rlib" "/Users/john/Development/pathfinder/target/release/deps/libmemchr-ae03ab047280892c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libstate-6a9076bbbd042f2a.rlib" "/Users/john/Development/pathfinder/target/release/deps/libnum_iter-949fe98fba35084d.rlib" "/Users/john/Development/pathfinder/target/release/deps/libnum_integer-7c9ed7024dd2cb3e.rlib" "/Users/john/Development/pathfinder/target/release/deps/libnum_traits-8b2b878320ce612a.rlib" "/Users/john/Development/pathfinder/target/release/deps/librsvg-a9e48537a7ca3349.rlib" "/Users/john/Development/pathfinder/target/release/deps/libbitflags-ff5a7f3bce313f27.rlib" "/Users/john/Development/pathfinder/target/release/deps/libgdk_pixbuf-00f751fb3b0fc3bf.rlib" "/Users/john/Development/pathfinder/target/release/deps/librsvg_sys-ff3b0520600cd849.rlib" "/Users/john/Development/pathfinder/target/release/deps/libatk_sys-54a3393c98f6fa78.rlib" "/Users/john/Development/pathfinder/target/release/deps/libarrayvec-b0e8c007bcd634c6.rlib" "/Users/john/Development/pathfinder/target/release/deps/libnodrop-8c2fe7b8fc85819d.rlib" "/Users/john/Development/pathfinder/target/release/deps/librustc_serialize-092b25a0f0bfedc0.rlib" "/Users/john/Development/pathfinder/target/release/deps/libbit_vec-ed1aa694d0488dca.rlib" "/Users/john/Development/pathfinder/target/release/deps/libunicase-42fc1583ba4b473d.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblazy_static-f31ca03d5f60d94e.rlib" "/Users/john/Development/pathfinder/target/release/deps/libsmallvec-96e7ad43bc591c00.rlib" "/Users/john/Development/pathfinder/target/release/deps/libinflate-e647e59deb02c338.rlib" "/Users/john/Development/pathfinder/target/release/deps/libadler32-dc2c2691dbab8075.rlib" "/Users/john/Development/pathfinder/target/release/deps/libgdk_sys-569721014253695a.rlib" "/Users/john/Development/pathfinder/target/release/deps/libpango_sys-85a199edf0c89ef9.rlib" "/Users/john/Development/pathfinder/target/release/deps/libgdk_pixbuf_sys-51294512f7ace60c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libgio_sys-a5fcef61987ca0f7.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblzw-af8d40f5ab43f02b.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcore_foundation_sys-6ce3677349c480a2.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcairo-2d1e34ff31c5914b.rlib" "/Users/john/Development/pathfinder/target/release/deps/libglib-ec0f51d04f0c5d77.rlib" "/Users/john/Development/pathfinder/target/release/deps/libgobject_sys-e3c8bf26a5851c05.rlib" "/Users/john/Development/pathfinder/target/release/deps/libglib_sys-ca13574a34f5f2d2.rlib" "/Users/john/Development/pathfinder/target/release/deps/libbitflags-01b71de7af22f59c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libc_vec-045cb6542998ed9c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcairo_sys-5c5ec73b81cf7d6b.rlib" "/Users/john/Development/pathfinder/target/release/deps/libtime-13528baabdb19989.rlib" "/Users/john/Development/pathfinder/target/release/deps/libmime-0bb00d243082265d.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblog-dc685e9668d6dfb5.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblog-ef8cc552acd1483c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcfg_if-2095f5ece6e2699c.rlib" "/Users/john/Development/pathfinder/target/release/deps/libminiz_sys-626e63d7dbedfed6.rlib" "/Users/john/Development/pathfinder/target/release/deps/libitoa-4081841efca00c1a.rlib" "/Users/john/Development/pathfinder/target/release/deps/librayon_core-6d9bf36b97a97e4a.rlib" "/Users/john/Development/pathfinder/target/release/deps/librand-2e644a6224c6dcd8.rlib" "/Users/john/Development/pathfinder/target/release/deps/libnum_cpus-3307841d9b8c74ed.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblibc-f5b4d9a81d58b480.rlib" "/Users/john/Development/pathfinder/target/release/deps/liblazy_static-5399fec565d99bbf.rlib" "/Users/john/Development/pathfinder/target/release/deps/libcoco-ee58dcae75858305.rlib" "/Users/john/Development/pathfinder/target/release/deps/libscopeguard-03b77b36e03298cf.rlib" "/Users/john/Development/pathfinder/target/release/deps/libeither-8049c2bcf01be3af.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-824cdc78ee5a36cd.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-bbf861ef3597975d.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-8c2857d1b85e8c41.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-5a3b31a86808b44a.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_system-f339fd16ebce237f.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-b846ed2c0a132808.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-393af31f543fb01f.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_unicode-66e8e2f35c10e521.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-a098f9eb2d797844.rlib" "/Users/john/.rustup/toolchains/nightly-2017-12-21-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f84959feb443b40b.rlib" "-framework" "ApplicationServices" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-framework" "CoreGraphics" "-l" "c++" "-l" "freetype" "-framework" "Security" "-l" "rsvg-2" "-l" "atk-1.0" "-l" "gdk-3" "-l" "pango-1.0" "-l" "gdk_pixbuf-2.0" "-l" "gio-2.0" "-framework" "CoreFoundation" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "gobject-2.0" "-l" "cairo" "-l" "System" "-l" "resolv" "-l" "pthread" "-l" "c" "-l" "m"
  = note: ld: library not found for -lrsvg-2
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Solved with `brew install librsvg`. Then a similar error but for `-latk-1.0` -- `brew install atk`. Then a similar error but for `-lgdk-3`, at which point I gave up.

**Comment by pcwalton** [comment]
I believe this should be fixed now by making those dependencies opt-in, but because of the nature of this bug I can't be sure. Please feel free to reopen if you still see any issues.
