### ISSUE TITLE
More stroke path problems

### ISSUE THREAD

**Issue by dylanede** [pcwalton/pathfinder#58]
As well as the problems reported in #57, which I've added some more screenshots to to show that the path closing bug has not been entirely fixed after the issue was closed, I've found some other problems with strokes, which appear to have been introduced by some of the fixes for #57, or at least significantly worsened.

Here is an SVG (again, uploaded as a zip since GitHub does not allow SVGs to be directly uploaded:
 [shaldon_bridge.zip](https://github.com/pcwalton/pathfinder/files/1579545/shaldon_bridge.zip)

This is what other SVG rendering implementations draw it as:

![image](https://user-images.githubusercontent.com/10339269/34260835-12f80ff2-e65f-11e7-95be-97dbc171dc82.png)

This is how it appears in the Pathfinder demo with XCAA (ignore the line width difference due to hard-coded limits in the demo):

![image](https://user-images.githubusercontent.com/10339269/34260872-2eb94594-e65f-11e7-8104-8ecd201860fa.png)

And with no AA:

![image](https://user-images.githubusercontent.com/10339269/34261031-b1268366-e65f-11e7-88e0-6b4e1eba864c.png)

And here is how it appears in a renderer I am writing that uses Pathfinder (no AA yet):

![image](https://user-images.githubusercontent.com/10339269/34260914-4d9f95f8-e65f-11e7-9990-f4cc37f4e6ca.png)

The problems due to round line joins and caps not being implemented should be ignored. The main problem that makes this unusable at the moment are the triangle spikes. In some scenes I have tested, these triangle spikes can be huge, and completely obscure the rest of the scene.

The other problem visible is the variable width of the strokes, though this may be part of the same problem.

**Comment by pcwalton** [comment]
This is probably floating point error again. Sigh.

**Comment by dylanede** [comment]
Just a note that your fixes for this are working well for me. Thanks!
