### ISSUE TITLE
GLSL 4.10 is not supported

### ISSUE THREAD

**Issue by awalgarg** [pcwalton/pathfinder#6]
Running this on Arch Linux, x64, Intel CPU with Intel integrated graphics, I get this panic on running the example:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompileFailed("Tessellation control shader", "0:11(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, 3.00 ES, and 3.10 ES\n\u{0}")', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
```

The error message seems pretty descriptive - GLSL 4.10 is not supported, but it supports previous versions correctly, so I guess support is yet to be added for the newer version?

**Comment by awalgarg** [comment]
bah, nvm, reported here already: https://github.com/pcwalton/pathfinder/issues/4

**Comment by pcwalton** [comment]
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment]
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.
