### ISSUE TITLE
Clarify required WebGL extensions

### ISSUE THREAD

**Issue by jfirebaugh** [pcwalton/pathfinder#62]
I see that the demo [requires](https://github.com/pcwalton/pathfinder/blob/1102965f6d261b1e4d4c65164f34a6cde3c834b6/demo/client/src/view.ts#L268-L276) the following WebGL extensions:

* EXT_color_buffer_half_float
* ANGLE_instanced_arrays
* OES_texture_half_float
* EXT_disjoint_timer_query
* OES_vertex_array_object
* EXT_frag_depth
* OES_element_index_uint
* OES_texture_float
* WEBGL_depth_texture

Of these, it doesn't look like `EXT_color_buffer_half_float` or `EXT_frag_depth` are actually used. Is it safe to remove the `getExtension` calls for them?

**Comment by pcwalton** [comment]
We do render to floating point textures for monochrome XCAA...

**Comment by jfirebaugh** [comment]
Isn't that via `OES_texture_half_float` though? [`colorBufferHalfFloatExt`](https://github.com/pcwalton/pathfinder/blob/1102965f6d261b1e4d4c65164f34a6cde3c834b6/demo/client/src/view.ts#L172) seems to be write-only, and the demo code doesn't call `gl.renderbufferStorage`.

**Comment by pcwalton** [comment]
Oh, according to https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_half_float enabling `OES_texture_half_float` implicitly enables `EXT_color_buffer_half_float`. Well, in that case, feel free to remove the latter.

**Comment by pcwalton** [comment]
This isn't really relevant anymore, because we don't use any extensions beyond standard GL3.

**Comment by pcwalton** [comment]
It might come up if we do a GLES2 port, but it's probably better to file another issue for that if and when that happens.
