### ISSUE TITLE
Document how to turn the contents of a MeshLibrary into vertex buffers, index buffers and textures for rendering

### ISSUE THREAD

**Issue by dylanede** [pcwalton/pathfinder#63]
Currently, the mapping from a MeshLibrary to the corresponding GPU resources used by shaders is unclear. Although the shaders now have documentation, there is none for how to produce the buffers they use. Prior to commit 6a640eca74ecb80a654ea9beeb39e4e684562def I had a fair idea of how to do this (at least for "direct" rendering) from looking at the source, but now it is becoming more difficult.

**Comment by pcwalton** [comment]
Pathfinder 3 no longer needs this.
