### ISSUE TITLE
Example fails on 2010 MBP

### ISSUE THREAD

**Issue by masklinn** [pcwalton/pathfinder#7]
It's one of the dead dGPU series so running on just the iGP, which is probably the cause but I figure I might as well report it.

Error (w/ backtrace):
```
thread 'main' panicked at 'Couldn't create a window!', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/option.rs:715
stack backtrace:
   1:        0x1057f32da - std::sys::imp::backtrace::tracing::imp::write::hd3b65cdfe843284c
   2:        0x1057f49ff - std::panicking::default_hook::{{closure}}::hf2b7428652613d83
   3:        0x1057f46a7 - std::panicking::default_hook::h5da8f27db5582938
   4:        0x1057f4e66 - std::panicking::rust_panic_with_hook::hcef1e67c646c6802
   5:        0x1057f4d04 - std::panicking::begin_panic::hc2e8ca89533cd10d
   6:        0x1057f4c22 - std::panicking::begin_panic_fmt::h60990696c3c3a88d
   7:        0x1057f4b87 - rust_begin_unwind
   8:        0x10581c880 - core::panicking::panic_fmt::h10231c789bd0e97d
   9:        0x10581c8ed - core::option::expect_failed::h77d0b34eebcbdfc8
  10:        0x10574e2cb - lorem_ipsum::main::h449476b86ae0c048
  11:        0x1057f5c5a - __rust_maybe_catch_panic
  12:        0x1057f5206 - std::rt::lang_start::h87cb84a8b6cb187e
```

iGP spec (from System Report):

> Intel HD Graphics:
> 
>   Chipset Model:	Intel HD Graphics
>   Type:	GPU
>   Bus:	Built-In
>   VRAM (Dynamic, Max):	288 MB
>   Vendor:	Intel (0x8086)
>   Device ID:	0x0046
>   Revision ID:	0x0012
>   gMux Version:	1.9.21

OpenGL Extension Viewer report:

> Renderer: Apple Software Renderer 
> Vendor: Apple Inc.
>  Memory: 0 MB 
> Version: 4.1 APPLE-12.1.0
>  Device: MacBookPro6,2 
> Shading language version: 4.10 

> Core features
> v3.0 (100 % - 23/23)
>  v3.1 (100 % - 8/8) 
> v3.2 (100 % - 10/10)
>  v3.3 (100 % - 10/10)
>  v4.0 (100 % - 14/14)
>  v4.1 (100 % - 7/7)
>  v4.2 (15 % - 2/13)
>  v4.3 (0 % - 0/23)
>  v4.4 (0 % - 0/10)
>  v4.5 (0 % - 0/11)
>  vARB 2015 (0 % - 0/13)
>  vARB 2016 (0 % - 0/1)

**Comment by pcwalton** [comment]
Interesting. This may be a GLFW problem. What version of macOS are you running?

**Comment by masklinn** [comment]
10.11.6 (latest El Capitan, not running Sierra yet)

**Comment by pcwalton** [comment]
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment]
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.
