### ISSUE TITLE
Pathfinder incorrectly renders 'J' glyph from Inconsolata-Regular.ttf

### ISSUE THREAD

**Issue by jimblandy** [pcwalton/pathfinder#84]
When displaying the `'J'` glyph from [Inconsolata Regular][IR], the outline is incorrect. These are screenshots generated with wrench, but I've built the Pathfinder WebGL-based demo, and the problem appears there as well.

Without PathFinder:

![image](https://user-images.githubusercontent.com/751272/39908253-0cd81390-54a2-11e8-8ae7-e3e05903716f.png)

With PathFinder:

![image](https://user-images.githubusercontent.com/751272/39908271-1dfcd7f0-54a2-11e8-9d5b-88615551d6f0.png)

Note the sharp corner at the lower left of the 'J'.

[IR]: https://github.com/google/fonts/raw/master/ofl/inconsolata/Inconsolata-Regular.ttf

**Comment by pcwalton** [comment]
This is because of a problem in the font loader. I'm currently replacing the font loader with `font-kit`, which will include a unit test for this.

**Comment by pcwalton** [comment]
Fixed in local `font-kit`, testing change now.
