### ISSUE TITLE
Keep up to date documentation on the nightly version pathfinder builds on

### ISSUE THREAD

**Issue by dylanede** [pcwalton/pathfinder#86]
Lately I have been struggling to build pathfinder due to some of its dependencies that depend on unstable Rust not building on the nightlies I have tried. It would be helpful if the README contained this information.

**Comment by EisenbergEffect** [comment]
I haven't been able to get it to build any time in the last month.

**Comment by Bobo1239** [comment]
Usually using the latest nightly and running `cargo update` before compiling should work (it did for me just now). Rocket breaks somewhat regularly due to its nightly features but always gets updated quite quickly.

**Comment by EisenbergEffect** [comment]
When attempting to follow the steps to run the demo from the readme, I get the following error using Pathfinder master with Rust nightly:

> failed to run custom build command for `fontsan v0.4.0 (https://github.com/servo/fontsan.git#29e879c8)`

I get this error both when executing the `npm run build` for the client and `cargo run --release`. The  same error causes both builds to fail. 

I could be doing something completely stupid. I don't have any experience with Rust. My interest is primarily in the WASM/WebGL render library that's used in the demo at the moment. I'm trying to choose between Pathfinder and the new Skia CanvasKit for a project of mine and was doing some evaluation to see where things are at.

**Comment by EisenbergEffect** [comment]
🎆 That fixed the latest issues. I'll submit a PR :)
