### ISSUE TITLE
Commit Cargo.lock for the demo server

### ISSUE THREAD

**Issue by dylanede** [pcwalton/pathfinder#87]
In combination with #86, this should help keep builds reproducible.

**Comment by dylanede** [comment]
Please @pcwalton could you commit your Cargo.lock. I still cannot find a nightly Rust version that will build the project and all of its dependencies from scratch. I believe this is due to overly permissive version bounds (notably no commit hash pinning for the github dependencies) in the demo server Cargo.toml. Committing the Cargo.lock should solve this.

Thanks!

**Comment by pcwalton** [comment]
Done.
