### ISSUE TITLE
Maybe rename the project

### ISSUE THREAD

**Issue by nox** [pcwalton/pathfinder#91]
There already exists a [pathfinder](https://crates.io/crates/pathfinder) crate.

**Comment by pcwalton** [comment]
That's unfortunate, but I've been calling this project Pathfinder for so long. Since Pathfinder is split up into multiple crates, I don't think this will end up being a problem—it'll just be kind of weird that `pathfinder` on crates.io isn't related to `pathfinder_font_renderer`, say.
